# This controller provides the catch-all action for React Router.
# This will render the bootstrap HTML file
# for all React Router requests.
#
# Unlike typical webpack or esbuild setups, we do not generate the bootstrap HTML file from ERB templates which include
# `javascript_include_tag` (propshaft, sprockets) or `javascript_pack_tag` (webpack).
# Instead, we take the index.html file that was generated by the React Router build
# and rename it to "react-router-rails-spa-index.html".
# We then serve this from the controller action in response to the bootstrap HTML file request.
#
# Benefits:
#
# * We can use the index.html file that React Router generates using SSG,
#   from the `frontend/app/root.tsx` file.
#   This file contains optimizations that would be challenging to recreate inside Rails using ERB templates.
# * By going through the Rails controller, we can adjust the cache and cookie headers to
#   improve performance, reliability, and integration with Rails.
#
# The included ReactRouterRailsSpa::CsrfCookieEnabled module will 
# send the CSRF token inside the "X-CSRF-Token" cookie for use inside your React app.
class ReactController < ApplicationController
  include ReactRouterRailsSpa::CsrfCookieEnabled

  def show
    render file: Rails.public_path.join("react/react-router-rails-spa-index.html"), layout: false
  end
end
