class ReactController < ApplicationController
  layout false

  # This is the catch-all action for React Router.
  # This will render the bootstrap HTML file
  # for all React Router requests.
  #
  # Unlike typical webpack or esbuild setups, we do not generate the bootstrap HTML file from ERB templates which include
  # `javascript_include_tag` (propshaft, sprockets) or `javascript_pack_tag` (webpack).
  # Instead, we take the index.html file that was generated by the React Router build
  # and rename it to "react-router-index.html".
  # We then serve this from a controller action in response to the bootstrap HTML file request.
  #
  # Benefits:
  #
  # * We can use the index.html file that React Router generates using SSG,
  #   from the `frontend/app/root.tsx` file.
  #   This file contains optimizations that would be challenging to recreate inside Rails using ERB templates.
  # * By going through the Rails controller, we can adjust cache and cookie headers to
  #   improve performance, reliability, and integration with Rails.
  def show
    render file: Rails.root.join("public", "react", "react-router-index.html")
  end
end
