class ReactController < ApplicationController
  layout false

  # This is the catch-all action for React Router. This will render the index.html file
  # for all React Router requests.
  #
  # Unlike typical webpack or esbuild setups, we do not render ERB files which include
  # `javascript_include_tag` (propshaft, sprockets) or `javascript_pack_tag` (webpack)
  # to load the React app.
  # Instead, take the index.html file that was generated by the React Router build
  # and rename it to "react-router-index.html".
  # This is served as a file from the controller in response to the bootstrap file request.
  #
  # Benefits:
  #
  # * We can use the index.html file that React Router generates as is.
  #   This file contains optimizations that would be challenging to recreate on the Rails-side.
  # * By going through the Rails controller, we can adjust cache and cookie headers to
  #   improve performance, reliability, and integration with Rails.
  def show
    render file: Rails.root.join("public", "react-router", "react-router-index.html")
  end
end
